### ISSUE TITLE
Port tests to Python 3

### ISSUE THREAD

**Issue by hadess** [TelepathyIM/telepathy-idle#7]
I've just had to disable telepathy-idle's test suite in Fedora because there are no Python 2 packages available there anymore. Ideally, those tests would be ported to Python 3 and reenabled.

**Comment by hadess** [comment]
See also https://github.com/TelepathyIM/telepathy-idle/pull/8

**Comment by Kaffeine** [comment]
Build with Python 3 is fixed for both `master` and `telepathy-idle-0.2` branches.
